# Generated by Django 6.0.6 on 2026-06-15 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('factory_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispatch_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='active', max_length=10)),
            ],
        ),
    ]
