# Generated by Django 6.0.6 on 2026-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_box',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
