# Generated by Codex on 2026-06-23

import uuid

from django.db import migrations


def _table_exists(cursor, table_name):
    cursor.execute("SELECT to_regclass(%s)", [table_name])
    return cursor.fetchone()[0] is not None


def _column_type(cursor, table_name, column_name):
    cursor.execute(
        """
        SELECT data_type
        FROM information_schema.columns
        WHERE table_name = %s AND column_name = %s
        """,
        [table_name, column_name],
    )
    row = cursor.fetchone()
    return row[0] if row else None


def _column_exists(cursor, table_name, column_name):
    return _column_type(cursor, table_name, column_name) is not None


def _drop_column_fk_constraints(schema_editor, table_name, column_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)

    for name, meta in constraints.items():
        if meta.get('foreign_key') and column_name in meta.get('columns', []):
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{name}"'
            )


def _drop_primary_key_constraints(schema_editor, table_name):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)

    for name, meta in constraints.items():
        if meta.get('primary_key'):
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" DROP CONSTRAINT "{name}"'
            )


def _convert_product_pk_to_uuid(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    product_table = 'products_product'
    ref_tables = [
        ('shipments_shipmentitem', 'shipments_shipmentitem_product_id_products_fk'),
        ('reception_deliveryitem', 'reception_deliveryitem_product_id_products_fk'),
    ]

    with schema_editor.connection.cursor() as cursor:
        if not _table_exists(cursor, product_table):
            return

        product_id_type = _column_type(cursor, product_table, 'id')
        if product_id_type == 'uuid':
            return
        if product_id_type != 'bigint':
            raise RuntimeError(
                f'Unsupported products_product.id type: {product_id_type}'
            )

        cursor.execute(
            'CREATE TEMP TABLE product_id_uuid_map '
            '(old_id bigint PRIMARY KEY, new_id uuid NOT NULL)'
        )
        cursor.execute(f'SELECT id FROM "{product_table}" ORDER BY id')
        for (old_id,) in cursor.fetchall():
            cursor.execute(
                'INSERT INTO product_id_uuid_map (old_id, new_id) VALUES (%s, %s)',
                [old_id, uuid.uuid4()],
            )

    for table_name, _constraint_name in ref_tables:
        with schema_editor.connection.cursor() as cursor:
            table_exists = _table_exists(cursor, table_name)
            product_id_type = _column_type(cursor, table_name, 'product_id')
            product_uuid_exists = _column_exists(cursor, table_name, 'product_uuid')

        if not table_exists or product_id_type == 'uuid':
            continue

        if product_id_type != 'bigint':
            raise RuntimeError(
                f'Unsupported {table_name}.product_id type: {product_id_type}'
            )

        _drop_column_fk_constraints(schema_editor, table_name, 'product_id')
        if not product_uuid_exists:
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" ADD COLUMN product_uuid uuid'
            )
        schema_editor.execute(
            f'''
            UPDATE "{table_name}" AS ref
            SET product_uuid = mapping.new_id
            FROM product_id_uuid_map AS mapping
            WHERE ref.product_id = mapping.old_id
            '''
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f'''
                SELECT COUNT(*)
                FROM "{table_name}"
                WHERE product_id IS NOT NULL AND product_uuid IS NULL
                '''
            )
            missing_count = cursor.fetchone()[0]
        if missing_count:
            raise RuntimeError(
                f'Cannot convert {table_name}.product_id: '
                f'{missing_count} rows have no matching Product'
            )

    _drop_primary_key_constraints(schema_editor, product_table)
    schema_editor.execute(f'ALTER TABLE "{product_table}" ADD COLUMN uuid_id uuid')
    schema_editor.execute(
        f'''
        UPDATE "{product_table}" AS product
        SET uuid_id = mapping.new_id
        FROM product_id_uuid_map AS mapping
        WHERE product.id = mapping.old_id
        '''
    )
    schema_editor.execute(f'ALTER TABLE "{product_table}" ALTER COLUMN uuid_id SET NOT NULL')
    schema_editor.execute(f'ALTER TABLE "{product_table}" DROP COLUMN id')
    schema_editor.execute(f'ALTER TABLE "{product_table}" RENAME COLUMN uuid_id TO id')
    schema_editor.execute(f'ALTER TABLE "{product_table}" ADD PRIMARY KEY (id)')

    for table_name, constraint_name in ref_tables:
        with schema_editor.connection.cursor() as cursor:
            table_exists = _table_exists(cursor, table_name)
            product_uuid_exists = _column_exists(cursor, table_name, 'product_uuid')
            product_id_type = _column_type(cursor, table_name, 'product_id')

        if not table_exists or not product_uuid_exists:
            continue
        if product_id_type == 'bigint':
            schema_editor.execute(f'ALTER TABLE "{table_name}" DROP COLUMN product_id')
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" RENAME COLUMN product_uuid TO product_id'
            )
        schema_editor.execute(
            f'ALTER TABLE "{table_name}" ALTER COLUMN product_id SET NOT NULL'
        )
        schema_editor.execute(
            f'''
            ALTER TABLE "{table_name}"
            ADD CONSTRAINT "{constraint_name}"
            FOREIGN KEY (product_id)
            REFERENCES "{product_table}" (id)
            DEFERRABLE INITIALLY DEFERRED
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pieces_per_box'),
    ]

    operations = [
        migrations.RunPython(
            _convert_product_pk_to_uuid,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
