# Generated by Django 6.0.6 on 2026-06-15 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_id', models.UUIDField(help_text='ID склада получателя')),
                ('delivery_number', models.CharField(help_text='Номер поставки', max_length=100, unique=True)),
                ('delivered_at', models.DateTimeField(help_text='Дата и время доставки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает приемки'), ('accepted', 'Принято полностью'), ('accepted_with_discrepancy', 'Принято с расхождениями'), ('cancelled', 'Отменено')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Общая сумма принятого товара', max_digits=14)),
                ('warehouse_comment', models.TextField(blank=True, help_text='Комментарий заведующего складом')),
            ],
            options={
                'verbose_name': 'Поставка от завода',
                'verbose_name_plural': 'Поставки от завода',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_qty', models.PositiveIntegerField(help_text='Ожидаемое количество (в штуках)')),
                ('actual_qty', models.PositiveIntegerField(blank=True, help_text='Фактическое количество (в штуках)', null=True)),
                ('discrepancy_type', models.CharField(choices=[('none', 'Нет расхождений'), ('shortage', 'Недостача'), ('surplus', 'Излишек'), ('defect', 'Брак')], default='none', help_text='Тип расхождения', max_length=20)),
                ('discrepancy_qty', models.IntegerField(default=0, help_text='Количество расхождения (положительное число)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Товар в поставке',
                'verbose_name_plural': 'Товары в поставках',
            },
        ),
    ]
