# Generated by Django 6.0.6 on 2026-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorydelivery',
            name='client_id',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factorydelivery',
            name='operation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
