# Generated by Codex on 2026-07-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_factorydelivery_client_id_and_more'),
        ('shipments', '0003_shipmentitem_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorydelivery',
            name='shipment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='deliveries',
                to='shipments.shipment',
            ),
        ),
    ]
