# Generated by Django 6.0.6 on 2026-06-16 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Сначала удаляем поле Integer
        migrations.RemoveField(
            model_name='warehousedebt',
            name='warehouse_id',
        ),
        # Добавляем поле UUID заново
        migrations.AddField(
            model_name='warehousedebt',
            name='warehouse_id',
            field=models.UUIDField(unique=True, default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='FactoryPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('card', 'Карта')], default='cash', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField()),
                ('client_id', models.CharField(max_length=36, unique=True)),
                ('operation_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платеж от завода',
                'verbose_name_plural': 'Платежи от завода',
                'db_table': 'factory_payments',
            },
        ),
    ]
