# Generated by Django 6.0.6 on 2026-06-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_warehousedebt_warehouse_id_factorypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousedebt',
            name='warehouse_id',
            field=models.UUIDField(unique=True),
        ),
    ]
