# Generated by Django 6.0.6 on 2026-06-15 16:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_id', models.UUIDField()),
                ('shipment_date', models.DateField()),
                ('truck_number', models.CharField(max_length=50)),
                ('truck_driver', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('accepted', 'Accepted'), ('accepted_with_discrepancy', 'Accepted With Discrepancy')], default='in_transit', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_boxes', models.PositiveBigIntegerField()),
                ('qty_pieces', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
