# Generated by Codex on 2026-06-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipments.shipment'),
        ),
    ]
